# Generated by Django 4.1.7 on 2023-03-24 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_finds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='vendor',
        ),
    ]
