# Generated by Django 4.1.7 on 2023-03-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_finds', '0003_alter_products_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.BooleanField(default=False, help_text='0-show,1-hidden'),
        ),
    ]
