# Generated by Django 4.1.7 on 2023-04-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_finds', '0006_bag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='catagory',
            name='status',
            field=models.BooleanField(default=False, help_text='0-instock,1-outstock'),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.BooleanField(default=False, help_text='0-instock,1-outstock'),
        ),
    ]
